# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 29719b494c832ece1ee7ecfb5e434be9e43b66a13c7c776c9e874c87889387722d573cccb5deaad583f054baaf049d2d1f4b8ffe755cd79840d89abc65acde21

test:
  secret_key_base: e61887da7d5ebd4552323ebb46cd671925e294fe303bd8a73a14f79128ff3f7dbc607389d70035ccf53af89f987d54e07a6358889962e389d0ccb855e450c27a

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
